/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.airline;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author N TECH
 */
public class GetTicket extends javax.swing.JInternalFrame {

    /**
     * Creates new form GetTicket
     */
    public GetTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ticketIdLabel = new javax.swing.JLabel();
        ticketIdTextField = new javax.swing.JTextField();
        getTicketButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        departureLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        arrivalLabel = new javax.swing.JLabel();
        contactNoLabel = new javax.swing.JLabel();
        flightNameLabel = new javax.swing.JLabel();
        firstNamejLabel1 = new javax.swing.JLabel();
        lastNamejLabel2 = new javax.swing.JLabel();
        genderjLabel3 = new javax.swing.JLabel();
        flightNamejLabel4 = new javax.swing.JLabel();
        departurejLabel6 = new javax.swing.JLabel();
        arrivaljLabel5 = new javax.swing.JLabel();
        contactNojLabel7 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        ticketIdLabel.setBackground(new java.awt.Color(0, 51, 255));
        ticketIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ticketIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        ticketIdLabel.setText("Ticket ID");

        ticketIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketIdTextFieldActionPerformed(evt);
            }
        });

        getTicketButton.setText("Get Ticket");
        getTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTicketButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        jLabel2.setBackground(new java.awt.Color(0, 51, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thanks for Choosing Jinnah AirLine");

        firstNameLabel.setBackground(new java.awt.Color(0, 51, 255));
        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        firstNameLabel.setText("First Name");

        lastNameLabel.setBackground(new java.awt.Color(0, 51, 255));
        lastNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLabel.setText("Last Name");

        departureLabel.setBackground(new java.awt.Color(0, 51, 255));
        departureLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        departureLabel.setForeground(new java.awt.Color(255, 255, 255));
        departureLabel.setText("Departure");

        genderLabel.setBackground(new java.awt.Color(0, 51, 255));
        genderLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel.setText("Gender");

        arrivalLabel.setBackground(new java.awt.Color(0, 51, 255));
        arrivalLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        arrivalLabel.setForeground(new java.awt.Color(255, 255, 255));
        arrivalLabel.setText("Arrival");

        contactNoLabel.setBackground(new java.awt.Color(0, 51, 255));
        contactNoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        contactNoLabel.setForeground(new java.awt.Color(255, 255, 255));
        contactNoLabel.setText("Contact No.");

        flightNameLabel.setBackground(new java.awt.Color(0, 51, 255));
        flightNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        flightNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        flightNameLabel.setText("Flight Name");

        firstNamejLabel1.setBackground(new java.awt.Color(0, 0, 204));
        firstNamejLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        firstNamejLabel1.setForeground(new java.awt.Color(255, 255, 255));

        lastNamejLabel2.setBackground(new java.awt.Color(0, 0, 204));
        lastNamejLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lastNamejLabel2.setForeground(new java.awt.Color(255, 255, 255));

        genderjLabel3.setBackground(new java.awt.Color(0, 0, 204));
        genderjLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        genderjLabel3.setForeground(new java.awt.Color(255, 255, 255));

        flightNamejLabel4.setBackground(new java.awt.Color(0, 0, 204));
        flightNamejLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        flightNamejLabel4.setForeground(new java.awt.Color(255, 255, 255));

        departurejLabel6.setBackground(new java.awt.Color(0, 0, 204));
        departurejLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        departurejLabel6.setForeground(new java.awt.Color(255, 255, 255));

        arrivaljLabel5.setBackground(new java.awt.Color(0, 0, 204));
        arrivaljLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        arrivaljLabel5.setForeground(new java.awt.Color(255, 255, 255));

        contactNojLabel7.setBackground(new java.awt.Color(0, 0, 204));
        contactNojLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        contactNojLabel7.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(firstNameLabel)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(genderLabel)
                        .addComponent(lastNameLabel)))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(genderjLabel3)
                        .addGap(89, 89, 89)
                        .addComponent(flightNameLabel)
                        .addGap(29, 29, 29)
                        .addComponent(flightNamejLabel4))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(firstNamejLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lastNamejLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(arrivalLabel)
                            .addGap(62, 62, 62))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(departureLabel)
                            .addGap(40, 40, 40)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(contactNoLabel)
                        .addGap(33, 33, 33)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactNojLabel7)
                    .addComponent(departurejLabel6)
                    .addComponent(arrivaljLabel5))
                .addGap(70, 70, 70))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(arrivalLabel)
                    .addComponent(firstNamejLabel1)
                    .addComponent(arrivaljLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(departureLabel)
                            .addComponent(departurejLabel6))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactNoLabel)
                            .addComponent(contactNojLabel7))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameLabel)
                            .addComponent(lastNamejLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderLabel)
                            .addComponent(flightNameLabel)
                            .addComponent(genderjLabel3)
                            .addComponent(flightNamejLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(ticketIdLabel)
                        .addGap(60, 60, 60)
                        .addComponent(ticketIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(getTicketButton)))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ticketIdLabel)
                    .addComponent(ticketIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getTicketButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTicketButtonActionPerformed
    String ticketID = ticketIdTextField.getText().trim(); 

    if (ticketID.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a Ticket ID.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        Connection con;
        PreparedStatement pre;
        
        Class.forName("com.mysql.cj.jdbc.Driver"); // use cj for latest versions
        con = DriverManager.getConnection("jdbc:mysql://localhost/Airline_Project", "root", "1234");
        
        String query = "SELECT * FROM Ticket WHERE TicketID = ?";
        pre = con.prepareStatement(query);
        pre.setString(1, ticketID);

        ResultSet rs = pre.executeQuery();

        if (rs.next()) {
            
            flightNamejLabel4.setText(rs.getString("FlightName")); 
            firstNamejLabel1.setText(rs.getString("FirstName"));         // First Name
            lastNamejLabel2.setText(rs.getString("LastName"));           // Last Name
            genderjLabel3.setText(rs.getString("Gender"));               // Gender
            flightNamejLabel4.setText(rs.getString("FlightName"));       // Flight Name
            arrivaljLabel5.setText(rs.getString("Arrival"));             // Arrival
            departurejLabel6.setText(rs.getString("Departure"));         // Departure
            contactNojLabel7.setText(rs.getString("Contact"));           // Contact No.
        } else {
            JOptionPane.showMessageDialog(this, "No ticket found with ID: " + ticketID, "Not Found", JOptionPane.INFORMATION_MESSAGE);
        }

        rs.close();
        pre.close();
        con.close();

    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_getTicketButtonActionPerformed

    private void ticketIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketIdTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrivalLabel;
    private javax.swing.JLabel arrivaljLabel5;
    private javax.swing.JLabel contactNoLabel;
    private javax.swing.JLabel contactNojLabel7;
    private javax.swing.JLabel departureLabel;
    private javax.swing.JLabel departurejLabel6;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel firstNamejLabel1;
    private javax.swing.JLabel flightNameLabel;
    private javax.swing.JLabel flightNamejLabel4;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel genderjLabel3;
    private javax.swing.JButton getTicketButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel lastNamejLabel2;
    private javax.swing.JLabel ticketIdLabel;
    private javax.swing.JTextField ticketIdTextField;
    // End of variables declaration//GEN-END:variables
}
